### ISSUE TITLE
Few issues I've noticed.

### ISSUE THREAD

**Issue by JohnEdwa** [akgunter/crt-royale-reshade#1]
I don't have prior experience with CRT-Royale so I can't say if these are issues with it or with your port, but...

* Setting "Border Size" to 0 seems to result in a black image. 0.01 works fine.

* There is something odd going on with the content box. 
If I set it up what seems to be properly for CrossCode, [1704x960 as seen here](https://user-images.githubusercontent.com/5417183/103595694-c47e3100-4f04-11eb-8bc7-8e64c745bbbd.png), the resulting [rendered image is way smaller than what it is supposed to be.](https://user-images.githubusercontent.com/5417183/103595703-c8aa4e80-4f04-11eb-9d08-073224a22b89.png)    
To make it work, I have to set the content to be 1905x1075, but doing so causes it to scale the image wrong causing non-integer pixel movement.

* I don't seem to have scanlines. At all.
If I load the default settings and change "Mask Type" to 0 to get the linear aperture grille mask, it produces the following, which is quite far off from the ["default settings" example shown on EmuGen wiki.](https://emulation.gametechwiki.com/images/4/45/CRT-Royale.png): 
![royaledefault](https://user-images.githubusercontent.com/5417183/103594565-b4188700-4f01-11eb-9f47-bf381edb21c9.png)

**Comment by DevonCM** [comment]
Yeah it seems to work a lot differently than in RetroArch, but I'm not smart enough to know whether that's because of how it was ported and how ReShade works comparatively, or if it's because of the games/resolution being different.
Like at 240p in RetroArch on SNES and PS1 games I have it looking amazing, but with ReShade in Blasphemous I can't get it to look good.  That's supposedly 640x360 native, but I don't know how the resolution actually affects the shader, and the game probably scales the resolution internally before ReShade can get to it.
Maybe if there were a field to manually enter the resolution that you want it to process rather than detecting it automatically then it would work better?  On that note, is there anything in ReShade to do that already?

Anyway, I hope more work can be done to improve this port because the potential is huge.

**Comment by akgunter** [comment]
> 
> 
> I don't have prior experience with CRT-Royale so I can't say if these are issues with it or with your port, but...
> 
>     * Setting "Border Size" to 0 seems to result in a black image. 0.01 works fine.
> 
>     * There is something odd going on with the content box.
>       If I set it up what seems to be properly for CrossCode, [1704x960 as seen here](https://user-images.githubusercontent.com/5417183/103595694-c47e3100-4f04-11eb-8bc7-8e64c745bbbd.png), the resulting [rendered image is way smaller than what it is supposed to be.](https://user-images.githubusercontent.com/5417183/103595703-c8aa4e80-4f04-11eb-9d08-073224a22b89.png)
>       To make it work, I have to set the content to be 1905x1075, but doing so causes it to scale the image wrong causing non-integer pixel movement.
> 
>     * I don't seem to have scanlines. At all.
>       If I load the default settings and change "Mask Type" to 0 to get the linear aperture grille mask, it produces the following, which is quite far off from the ["default settings" example shown on EmuGen wiki.](https://emulation.gametechwiki.com/images/4/45/CRT-Royale.png):

You're right. The "Border Size" thing shouldn't be happening, and the cropping logic is being bizarre. The border size issue is likely a small residual artifact from the port, but the cropping issue is weird. Maybe I did something wrong with the y-axis math.

The scanlines are kind of a mess right now. For one, crt-royale tries to automatically figure out if the signal is interlaced or not based on the input resolution; and that doesn't play nicely with ReShade's sitting on top of the viewport. On top of that, you can force them for 1080p content with the "Assume 1080 signal is 1080i" setting, but it looks horrendous right now. I suspect I'll have to rewrite that whole feature from scratch.


> Yeah it seems to work a lot differently than in RetroArch, but I'm not smart enough to know whether that's because of how it was ported and how ReShade works comparatively, or if it's because of the games/resolution being different.
> Like at 240p in RetroArch on SNES and PS1 games I have it looking amazing, but with ReShade in Blasphemous I can't get it to look good. That's supposedly 640x360 native, but I don't know how the resolution actually affects the shader, and the game probably scales the resolution internally before ReShade can get to it.
> Maybe if there were a field to manually enter the resolution that you want it to process rather than detecting it automatically then it would work better? On that note, is there anything in ReShade to do that already?
> 
> Anyway, I hope more work can be done to improve this port because the potential is huge.

The majority of the difference is probably in the scanlines. They force a very distinctive grid pattern onto the image that definitely can make it or break it.

As for resolution differences, things there are really difficult. The RetroArch version gets to sit inside the rendering pipeline and gets access to internal resolution data, and it's hooked directly into the pipeline's upscaling logic. ReShade on the other hand only sees the final result after all the resizing and whatnot is done. I've tried to mitigate some of this with the content box, and it seems to scale correctly with Super Metroid for me; but I'm sure there are plenty of configurations where the resolution stuff just doesn't behave. After the scanlines are working right, I can dig more into this.

**Comment by DevonCM** [comment]
Ah yeah so that explains my experience then.  It's probably going to be awkward depending on the game because with Blasphemous (the only pixel game I have to try) when I set the resolution to 640x360 in fullscreen (at least on a 3840x2160 display) it doesn't just "fill" the screen with the low res.  That's basically what it's doing when set to 4K anyway but obviously then ReShade doesn't see it like that.  And I'm not really equipped to know whether it's the game doing that, or something with my display's or PC's scaling... ugh

Then there are other modern pixel games that made the terrible design decision to use small high-res text rather than have a consistent resolution across all assets.  I would guess it's basically unusable in those cases since you can't nudge under the UI/text layer, and that would look stupid anyway.
I don't know what these fucking developers are thinking.  They should be implementing their own optimized CRT shaders into their games, or use a style that's not giant sharp square pixels.  I don't know why people find that aesthetically pleasing or acceptable on modern displays.
/rant

**Comment by JohnEdwa** [comment]
You need to run the game at your full-screen resolution, otherwise the shader is also limited to working at 640x360 which obviously doesn't work at all.

You can try playing around with a different shader called [Resolutionizer](https://github.com/Matsilagi/reshade-retroarch-shaders/blob/master/Shaders/Resolutionizer.fx) to force ReShade to downscale the game before it's passed to CRT-Royale. It's not as perfect as actually having the game render itself at a low pixel-perfect resolution, but when it hidden behind the CRT effects it isn't really that visible.

---

Also, for some weird reason, the default triad size in CRT-Royale is 3 even though the [textures are actually 8x8](https://github.com/akgunter/crt-royale-reshade/blob/master/reshade-shaders/Textures/crt-royale/TileableLinearApertureGrille15Wide8And5d5SpacingResizeTo64.png) (there is 3 red, 2 green, 3 blue) which means the pixel-perfect triad size option should be 4 (or 8), not 3. I would guess it's a leftover from when the shader was made, as 4 is simply just visually too large on 1080p resolutions.    
It's just odd the textures were never properly redone for a triad size of 3.

**Comment by akgunter** [comment]
I've pushed a branch `feature/scanline-fixes` that's worth checking out. I posted some commentary on it in Issue #2.

**Comment by akgunter** [comment]
Closing because all three of the original bugs and discrepancies are addressed now.

As for the thing about the 64-pixel PNGs for the phosphor masks, I'm pretty sure it's correct as-is. The 64-pixel version is just a lanczos-resized copy of the original 512-pixel version, and lanczos-resizing both down to triad size 3 produces nearly identical masks - which is precisely what you'd want. The reason for the 3-2-3 pattern is because the resampling is preserving the contribution from those black pixels on the ends without losing the apparent brightness of the red and blue. The green doesn't need the extra pixels because its two pixels are at their full brightness.

You can also qualitatively check this by playing with the triad size and the USE_LARGE_PHOSPHOR_MASK setting with sample mode 0. For triad sizes <= 8, the large and small masks produce nearly identical results. On top of that, toggling the entire shader on and off shows that the perceived colors look correct for both files. There probably is an alternative 48-pixel or 72-pixel mask that would also produce the same results, but the best you could hope for is a third mask that still looks the same.


For a smidget of clarification, the purpose of having both the 512 and 64 is to handle edge cases where one very blatantly does not work. Examples include triad size 4, sample mode 1 with the large mask and triad sizes >8 with the small texture. The rule for picking one over the other is "don't bother with it unless one isn't working right".
