### ISSUE TITLE
switch on interlacing and scanline keeps flickering

### ISSUE THREAD

**Issue by Arctic7** [akgunter/crt-royale-reshade#11]
I was running your crt-royale in a tft laptop, I used xebra emulator and epsxe emulator, both support crt-royale, when I turned on interlacing, the scanline keeps flickering, if I set scanline blend strength to 1, the scanline disappered, my laptop's refresh rate is 60fps, can you ajust your code to solve this problem? Thank you.

**Comment by akgunter** [comment]
The flickering is inherent to the unblended interlacing logic, and the blend strength setting is the solution. No, you won't see the lines in your screenshot because they're blended; but it should look nearly identical while you're playing because at 60 fps your eyes and LCD panel do that same blending anyway (give or take depending on your LCD panel).

The reason it flickers when unblended is because the scanline logic first draws the even-numbered rows on the first frame and then draws the odd-numbered rows on the next - just like a CRT does. In an ideal world, the emulator is synchronized well with your monitor; and it works great. In practice, many emulators w/ ReShade don't do vsync as well as RetroArch; and you get the occasional frame that hangs for a few more milliseconds than it should have. That smidget of latency is extremely noticeable and looks like flickering. (If you look reeeeaaally closely at the RetroArch version of crt-royale, you can see it flickering there too - just not as strongly because its vsync works super well).

Aside from setting the blend strength to 0.7 to 1.0'ish, you can try fiddling with the emulator's vsync setting; or you might be able to use your GPU's control panel to force vsync from there. Maaaaybe gsync and freesync would work even better if your hardware supports it. Unfortunately there really isn't anything else to be done as far as I'm aware.

**Comment by Arctic7** [comment]
> The flickering is inherent to the unblended interlacing logic, and the blend strength setting is the solution. No, you won't see the lines in your screenshot because they're blended; but it should look nearly identical while you're playing because at 60 fps your eyes and LCD panel do that same blending anyway (give or take depending on your LCD panel).
> 
> The reason it flickers when unblended is because the scanline logic first draws the even-numbered rows on the first frame and then draws the odd-numbered rows on the next - just like a CRT does. In an ideal world, the emulator is synchronized well with your monitor; and it works great. In practice, many emulators w/ ReShade don't do vsync as well as RetroArch; and you get the occasional frame that hangs for a few more milliseconds than it should have. That smidget of latency is extremely noticeable and looks like flickering. (If you look reeeeaaally closely at the RetroArch version of crt-royale, you can see it flickering there too - just not as strongly because its vsync works super well).
> 
> Aside from setting the blend strength to 0.7 to 1.0'ish, you can try fiddling with the emulator's vsync setting; or you might be able to use your GPU's control panel to force vsync from there. Maaaaybe gsync and freesync would work even better if your hardware supports it. Unfortunately there really isn't anything else to be done as far as I'm aware.

OK thanks, I guess it's a pity I can't emulate scanline effects in a lcd screen,  anyway good work on porting this shader to reshade.

**Comment by JohnEdwa** [comment]
Any chance of adding an option to disable or bypass that interlacing logic completely?
From what I can understand, telling the code to run the second pass using the current frame information instead of making it waiting for the next could possibly remove the flickering issue with the "downside" of also removing interlacing artifacts from a moving scene - something that I don't really care for in the first place.

**Comment by akgunter** [comment]
That option is already there actually. Just set Enable Interlacing to No, and it’ll disable bobbing and interlacing. My scanline rewrite also fixed the original shader’s issue of being way too bright when interlacing is disabled, so you shouldn’t have to mess with any color settings.
