### ISSUE TITLE
Might have found another rounding error?

### ISSUE THREAD

**Issue by MilkManEX** [akgunter/crt-royale-reshade#16]
Static interlacing with scanlines set to 2:
![KingOfFighters2002UM_x64 2021-12-31 09-43-52](https://user-images.githubusercontent.com/16171167/147829002-fcf8b1d3-1295-4798-af14-0b49492f27d4.png)

No interlacing with scanlines set to 4:
![KingOfFighters2002UM_x64 2021-12-31 09-44-19](https://user-images.githubusercontent.com/16171167/147829016-d543fcab-36ed-47ee-b345-fcb25cf25804.png)

For some reason, the static interlacing is very dark and gets darker near the bottom of the screen, but is generally more pixel-correct. No interlacing doesn't do the darkening thing, but it doesn't *quite* align with the image.

**Comment by Defreezer** [comment]
I might have found a similar problem at 1080p. Grille mask, Static Interlacing, Scanline Size 2, Gaussian Beam Shape, the rest is default.
It seems like there's something happening with the bloom. The problem seems to go away by raising the Downsampling Sharpness, but it also introduces even more bloom.
![4352624563](https://user-images.githubusercontent.com/79490923/148253297-c35a389d-6ab5-4a74-86f4-62fa01769009.png)

**Comment by akgunter** [comment]
So I was stumped for a while, and I think I just managed to stumble across another manifestation of the same bug. It's also a nasty one.

I think it's a kind of destructive interference between the gaussian scanlines and ReShade's built-in downsampling algorithm. The bloom and halation effects are just based on a blur effect, and the easiest way to do a blur is to read in from the screen, write out to a smaller texture, and then read back in later with interpolation. Voila, you have a blur effect that required like five lines of code. However the screen resolution isn't necessarily a multiple of that smaller texture's resolution, and the built-in downsampling algorithm produces sinusoidal artifacts in that case (ringing artifacts? I dunno what the correct term is). The interference pattern between those artifacts and the gaussian scanlines can screw with the halation and bloom effects. Particularly bad combinations can actually zero out that whole texture.

I think the fix will be implementing a more robust downsampling algorithm, assuming I can find one. I can also see if there's a way I can apply bloom and halation additively instead of multiplicatively, and that might prevent the interference pattern from zero'ing out the image.


As a side note, I think I remember this ticket originally referring to inconsistent brightness when changing the scanline width with a gaussian beam. I think that's a combination of this artifacting and a quirk in my gaussian math. Basically, the math is correct for a continuous space, but screens are pixelated and discreet and consequently the gaussian gets rasterized. That causes the total brightness to deviate from the correct brightness in a chaotic way. I assume the fix for that is to find a way to compute and counteract the effects of that rasterization. I'll need to fix the interference problem first, though, because that's a far larger component of the issue.

**Comment by akgunter** [comment]
Alright, got the downsampling fixed. I was able to recycle my existing Lanczos downsampling code, and it worked. It's probably overkill, but I can deal with that later if need be.

Now to fix the gaussian rasterization thing, so the brightness doesn't change so chaotically for narrow scanlines.

**Comment by Defreezer** [comment]
If I may mention a completely different matter, is it possible to add an extra option to reduce bloom underestimation without impacting the color grading of the image? The default value is rather intense on sub-4k monitors and reducing the values also removes contrast, which is very noticeable in games with bright colors.
![default bloom](https://user-images.githubusercontent.com/79490923/155846515-05d66359-9e7f-45e9-b377-3fee79881705.png)
![lessbloom](https://user-images.githubusercontent.com/79490923/155846518-ffe85ef5-abcb-4562-865f-d3a10a366401.png)

**Comment by akgunter** [comment]
Honestly... I wouldn't count on it for a while. That's an involved and convoluted segment of the pipeline where basically all of the colorization settings combine into one massive nonlinear mess of a transform. I'll have to figure out exactly how those settings all interact, and how they could be disentangled. It might even be the case that they shouldn't be disentangled.

I'm guessing that this is an artifact of the bloom math operating on an LCD. Bloom is meant to simulate the diffusion of light through the glass, which is subject to conservation of energy. Then the total energy emitted from the glass should be very slightly less than the energy emitted by the phosphors, so the image should probably tend to get a tiny bit dimmer with bloom enabled. But on an LCD, adding bloom too naively can cause pixels to light up that were otherwise dim. Then the bloom effect is making the screen emit more energy and will probably appear artificially brighter. Combine that with bloom being dependent on image brightness and colors being clamped to [0, 1], and you have the definition of color grading. It's very similar to the color grading issues that can happen with scanlines and interlacing.

If this is all correct, the heart of the fix would be to rewrite the bloom logic to be energy conserving and to write new logic that independently handles the contrast-enhancing effect that's currently rolled up into it.

**Comment by akgunter** [comment]
I've split this bloom weirdness off into its own ticket and will close this one out.

This ticket included a bug with bloom/halation, due to the downsampling passes. It also included the issue with narrow scanlines having inconsistent brightness. Both of these are resolved now.
