### ISSUE TITLE
Issue with vertical beam convergence offset

### ISSUE THREAD

**Issue by soinatos** [akgunter/crt-royale-reshade#23]
Hey, for some reason the default 0 values in the vertical beam offset options are just completely wrong for me. I've read and seen that it's supposed to basically be the perfect values if you want an accurate image, but it makes for example, whites just a mishmash of pink, green, yellow etc. for me.
Of course, I've tried to fix this by changing the offset of the vertical beam, but I just can't get it right. For example, I can get it almost perfect but then the red bleeds off from one side just barely and it's making me go insane. 
Any fix for this?

**Comment by akgunter** [comment]
Try installing the code from branch `feature/preproc-blur` (the entire codebase, not just the crt-royale.fx file). Perhaps rename your current preset, so you can get the default settings without blowing up the tweaks you've made so far.

That branch should be stable and has a bunch of updated math that might help. My guess is that the phosphor mask isn't playing nicely with your display resolution. I completely rewrote that part of the shader in my more recent branches, and in theory it's much less nitpicky now. At the very least, it should run faster.

Another thing you can try is fudging the CONTENT_WIDTH setting by 1 or 2 pixels and using the Border settings to hide artifacts on the edges of the screen.

Just in case it helps, I do recommend making sure you set Mask Size Param to "Triad Width" and then set Mask Triad Width to a multiple of 3. That tends to produce the best results.

**Comment by soinatos** [comment]
I tried the other code and it had the same problem. 
After that, tried the CONTENT_WIDTH thing but I wasn't quite sure what numbers to put in so I just started with 1, then 10, and that didn't do anything but make a black screen, I put 1000 and it crashed. Now every time I try to open the game it just crashes and ReShade keeps remembering my settings for the shader, even though I've tried 3 different versions of the installer ._.

**Comment by soinatos** [comment]
I tried the other code, same problems as before.
I also tried the CONTENT_WIDTH thing but wasn't sure what numbers to put in, so I started at 1, then 10, and that only produced a black screen so I put in 1000 and it just crashed. Now ReShade keeps remembering that I put in 1000 there and just keeps on crashing, I've tried 3 different versions of the installer and still the same thing ._.

(sorry about the closing and reopening lol, first time doing anything other than downloading stuff on github)

**Comment by akgunter** [comment]
Ah, yeah, that's not actually a bug. That's what happens when you draw a grille or slot mask directly to the screen. The left-most edge will be a column of red phosphors, without any blue or green ones to the left of it to balance out. The result is a red line on the side in some images. Other images will have a blue line on the right edge for the same reason.

The fix is to use the CONTENT_WIDTH and CONTENT_HEIGHT settings in the Preprocessor Definitions section, which tells the shader where the edges of your game actually are. Then it'll draw a border effect around it that will hide the artifact.

Given your screenshot, I think the correct values for you are CONTENT_HEIGHT to 1170 and CONTENT_WIDTH to 864. In general, check out the [content box section of the quickstart page](https://github.com/akgunter/crt-royale-reshade/wiki/Quickstart#configuring-the-content-box). That'll let you figure out the correct settings for other games or other window sizes.

**Comment by akgunter** [comment]
I'm gonna go ahead and close this out. Feel free to re-open it if I've missed anything, or open a new ticket if you encounter any other issues.
