### ISSUE TITLE
(Feature request, not an issue) NTSC/Composite filters

### ISSUE THREAD

**Issue by MilkManEX** [akgunter/crt-royale-reshade#9]
Is it possible to incorporate an NTSC and/or Composite filter? There were presets in Retroarch that combined the effects with CRT-Royale. There are [already some ports of Retroarch's NTSC filters](https://github.com/Matsilagi/reshade-retroarch-shaders), but they do their own interlacing that interacts poorly with CRT-Royale's.

**Comment by akgunter** [comment]
I wouldn't code them as a component of the crt-royale.fx shader itself, because that would veer too far away from this being a port; but there might be room to add some of them as standalone effects that you can place before crt-royale.fx in the pipeline. It might be a new set of files in this project, or a new set of files in Matsilagi's repo, or a brand new repo that you can install next to both of them.

I can't give a timeline on the idea, but I can at least start researching it.

**Comment by akgunter** [comment]
@MilkManEX have you taken a look at [Matsilagi's updated repo](https://github.com/Matsilagi/RSRetroArch)? Try loading some of those before crt-royale-reshade and tell me what you think.

**Comment by MilkManEX** [comment]
Oh wow, yeah NTSC_Retroarch_Gamma seems to accomplish exactly what I was hoping for. Thanks for the heads up!

**Comment by akgunter** [comment]
> Oh wow, yeah NTSC_Retroarch_Gamma seems to accomplish exactly what I was hoping for. Thanks for the heads up!

Awesome! If you find out an effect you need is missing, feel free to comment back in here; and I'll reopen the issue. Or post in Matsilagi's repo seeing as he's got the others. We've been working together on these, so a post in either place will get our attention.
